---
- name: Create temp file on nodes
  hosts: all
  become: true
 # vars:
    #JSON_DATA: '{"hosts": ["root@172.31.93.220"]}'
   # name: "{{ file_name }}"
  tasks:
    - name: Create temp file
      ansible.builtin.file:
        path: /tmp/saanvika
        state: touch
