pipeline {
    agent any

    parameters {
        string(name: 'JSON_DATA', defaultValue: '{"hosts": ["root@172.31.93.220"]}', description: 'Enter JSON data containing list of IP addresses')
        string(name: 'FILE_PATH', defaultValue: 'srilaxmi.txt', description: 'Enter the path where the temp file should be created')
    }

    stages {
        stage('Execute Ansible Playbook') {
            steps {
                script {
                    def jsonData = readJSON text: params.JSON_DATA
                    def hosts = jsonData.hosts.collect { it }
                    def inventoryPath = "${WORKSPACE}/inventory"
                    writeFile file: inventoryPath, text: "[nodes]\n" + hosts.join('\n')
                    sh "ansible-playbook -i ${inventoryPath} --extra-vars 'file_name=${params.FILE_PATH}' /var/lib/jenkins/workspace/playbook2.yml"
                }
            }
        }
    }
}
